services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=default_db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    ports:
      - '8000:8000'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=default_db
    depends_on:
      - db

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    command: bash -c "npm install && npm i -g @angular/cli@latest && ng serve --host 0.0.0.0 --port 4200"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
