services:
  db:
    container_name: db
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=default_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  web:
    container_name: backend
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    depends_on:
      - db
volumes:
  data-db:
