services:
  db:
    container_name: db
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - data-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=default_db

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    ports:
      - '8000:8000'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=default_db
    depends_on:
      - db
volumes:
  data-db:
