# Generated by Django 5.1.1 on 2024-09-27 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_workrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkUserProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_text', models.TextField()),
                ('cost', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='app.workrequest')),
            ],
        ),
    ]
