# Generated by Django 5.1.1 on 2024-09-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_user_address_remove_visa_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='doc_type',
            field=models.CharField(default='other', max_length=5),
        ),
    ]
