# Generated by Django 5.1.1 on 2024-10-03 01:51

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_user_status_user_worker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='worker',
            new_name='is_worker',
        ),
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[app.validators.validate_cpf]),
        ),
        migrations.AlterField(
            model_name='user',
            name='crea',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='passport_due',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='rg',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('new', 'Novo'), ('pending_documentation', 'Aguardando Documentação'), ('pending_aproval', 'Aguardando Aprovação'), ('suspended', 'Suspenso'), ('banned', 'Banido'), ('able', 'Apto')], default='new', max_length=50),
        ),
        migrations.AlterField(
            model_name='workuserproposal',
            name='cost',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
