# Generated by Django 5.1.1 on 2024-10-04 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_worker_user_is_worker_alter_user_cpf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cpf_document', to='app.files')),
                ('crea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crea_document', to='app.files')),
                ('passport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passport_document', to='app.files')),
                ('rg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rg_document', to='app.files')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
