# Generated by Django 5.1.1 on 2024-10-04 17:28

import app.models.users
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.FileField(default='settings.STATIC_URL/images.default_profile.jpg', upload_to=app.models.users.user_directory_path),
        ),
        migrations.AlterField(
            model_name='files',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
