# Generated by Django 5.1.1 on 2024-10-04 18:58

import app.models.users
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_user_profile_image_alter_files_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.FileField(default='settings.STATIC_URL/images/default_profile.jpg', upload_to=app.models.users.user_directory_path),
        ),
    ]
