# Generated by Django 5.1.1 on 2024-10-10 10:58

import app.models.users
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_user_profile_image_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.FileField(null=True, upload_to=app.models.users.user_directory_path),
        ),
    ]
