# Generated by Django 5.1.1 on 2024-10-14 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('new', 'Novo'), ('pending_documentation', 'Aguardando Documentação'), ('pending_aproval', 'Aguardando Aprovação'), ('suspended', 'Suspenso'), ('banned', 'Banido'), ('approved', 'Aprovado')], default='new', max_length=50),
        ),
    ]
