# Generated by Django 5.1.1 on 2024-11-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_user_managers_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='cpf_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='documents',
            name='crea_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='documents',
            name='passport_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='documents',
            name='rg_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
