# Generated by Django 5.1.1 on 2024-11-01 19:04

import app.models.files
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_documents_cpf_number_documents_crea_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='files',
            options={'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
        migrations.RemoveField(
            model_name='files',
            name='doc_type',
        ),
        migrations.RemoveField(
            model_name='files',
            name='lgpd',
        ),
        migrations.RemoveField(
            model_name='files',
            name='secure',
        ),
        migrations.RemoveField(
            model_name='files',
            name='upload_to',
        ),
        migrations.AddField(
            model_name='files',
            name='content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='files',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=app.models.files.user_directory_path),
        ),
        migrations.AddField(
            model_name='files',
            name='filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='files',
            name='size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='files',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='files',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
